### ISSUE TITLE
id_branch

### ISSUE THREAD

**Issue by papirnicek** [Zasilkovna/prestashop-1.6#1]
Chtěl bych vás požádat, zda by bylo možné informaci s adresou pobočky, která je nyní v administraci eshopu a v potvrzovacím emailu doplnit o číslo pobočky (id_branch). Např. "Zásilkovna (6709, Žďár nad Sázavou, nám. Republiky 4)".

Provádíme exporty a importy dat a vždy pracujeme s číslem pobočky. Bylo by skvělé, kdyby jsme ho nemuseli dohledávat na stránkách Zásilkovny,

Děkuji

**Comment by packeta** [comment]
Dobrý den, v příští verzi přidáme do seznamu objednávek pro Zásilkovnu za název pobočky i ID.  Do té doby můžete pro vaše účely využít csv export který modul nabízí pro export do Zásilkovny, kde je ID pobočky uvedeno. Pokud chcete export kde je název i ID pobočky, můžete využít funkci PrestaShopu - Nástroje/SQL manager, kde si export můžete jednoduše vytvořit.

**Comment by MatyasKoval** [comment]
Dobrý den,
jen pro upřesnění, tato funkce je nyní plánována do verze 3.0 našeho modulu.

S přáním krásného dne,
Matyáš Kovaľ - Technická podpora Zásilkovna
