### ISSUE TITLE
Feature request - možnost použití kódu objednávky namísto ID

### ISSUE THREAD

**Issue by 3rain** [Zasilkovna/prestashop-1.6#10]
Dobrý den,
V objednávkách používáme kód objednávky jako hlavní identifikátor. Např. zákazník jej vyplňuje jako variabilní symbol při platbě a je také zobrazen ve všech krocích procesu objednávky i v e-mailech.

Modul Zásilkovny však pracuje jen s ID objednávky. Toto ID se pak objeví v systému Zásilkovny i v e-mailech a asi i SMS, které Zásilkovna posílá zákazníkům. Tam může dojít ke zbytečnému zmatení, protože zákazník má od nás jiné číslo objednávky (kód).

Prestashop moduly běžně obsahují nastavení, zda použít ID nebo kód pro identifikaci objednávek. Chtěl bych vás poprosit o zvážení, zda by se toto nastavení dalo přidat do modulu. Věřím, že to lidé ocení.

Děkuji moc

![image](https://user-images.githubusercontent.com/81020682/111869800-4f59be00-8981-11eb-9826-07e80a0d1925.png)

**Comment by packeta** [comment]
Dobrý den,  děkujeme za váš návrh na vylepšení našeho modulu.  Tato možnost je určitě potřeba a proto jsme ji přidali do nadcházející verze 2.0.5 která přinese i implementaci nové verze widgetu v6 s podporou externích dopravců - https://blog.zasilkovna.cz/nova-verze-vyhledavace-vydejnich-mist-je-tu/.  Novou verzi bychom chtěli vydat do poloviny Dubna 2021.

**Comment by 3rain** [comment]
@packeta Dobrý den, vidím, že request je pořád open., ale 2.0.5 už šla ven. Zatím jsem ji neinstaloval, protože jsem nechtěl přepsat jeden workaround. Mohu se spolehnout, že poslední verze již obsahuje tuto změnu? Děkuji

**Comment by packeta** [comment]
Dokonce jsme dnes vydali verzi 2.0.6,  která mimo několika oprav přináší i novou funkci: Zobrazení informace o vybraném výdejní místě v posledním kroku objednávky, v emailu "potvrzení objednávky" a v detailu objednávky registrovaného uživatele.

Zobrazení kódu objednávky místo ID je implementováno od verze 2.0.5 (na uzavření issue se bohužel zapomnělo). 

V nastavení modulu si zvolíte , jaký údaj se má exportovat do Zásilkovny jako číslo objednávky:
![Modules_•_Zásilkovna](https://user-images.githubusercontent.com/57401091/123426595-e3ac7000-d5c3-11eb-850a-e66eaa3f2825.png)

V seznamu objednávek pak vidíte oba údaje:
![Zásilkovna_•_Zásilkovna](https://user-images.githubusercontent.com/57401091/123427359-d04dd480-d5c4-11eb-8eff-b81ef1e98e7f.png)

Pokud nám napíšete, co váš workaround řeší,  mohli bychom uvažovat o doplnění do oficiální verze.

**Comment by 3rain** [comment]
Super,

díky za odpověď. Byla to implementace toho reference ID.. Už se to bez toho
nedalo furt jen přepisovat ručně. Takže pokud už to funguje, tak to
nasadíme.

No uvidím až vyzkouším novou verzi, ale co nám se starší verzí nefunguje
dobře je tohle:
- nastavím si pobočku zásilkovny v kroku výběru dopravce
- jdu dál na platbu
- vrátím se
- pobočka je resetována a musím ji vybrat znovu

Hezký den

Ondra

**Comment by packeta** [comment]
To resetování výdejního místa při návratu z platby je i v nové verzi.   Hned zakládám issue a v příští verzi to zkusíme nějak vyřešit.  Děkuji za nahlášení.  Až tuto verzi vyzkoušíte,  budu rád když dáte vědět, jestli ten kód objednávky funguje jak má.  Do další verze ještě přemýšlím, že by bylo možné  vybírat mezi ID, kódem objednávky a číslem vystavení faktury.

**Comment by 3rain** [comment]
Tak to je fajn, díky za ochotu to řešit. Mějte se
