### ISSUE TITLE
Více než 1000 objednávek

### ISSUE THREAD

**Issue by martinpetracek** [Zasilkovna/prestashop-1.6#2]
Do objednávky 999 se vše zobrazovalo v "Export objednávek Zásilkovna", ale od 1000 výše se to již k exportu nenabízí.

**Comment by packeta** [comment]
U modulu není žádné omezení, které by zapříčinilo že objednávky s pořadovým číslem 1000 a více se nezobrazí.   Stejný dotaz jste nám poslal i na náš email, tady tedy problém uzavírám, abychom to neřešili duplicitně.

**Comment by martinpetracek** [comment]
Nevím jak to, ale po pár objednávkých už to zase začalo přenášet objednávky, viz komunikace na emailu. 
![image](https://user-images.githubusercontent.com/14837279/93085069-4ec03200-f695-11ea-8064-7d65d94bc80a.png)
Nevím, zda tomu pomohla aktualizace na 2.0.3 (objednávky které došly pak už s ní se zase objevují), ale to je asi spíše náhoda.
