### ISSUE TITLE
Carrier.php override - název pobočky

### ISSUE THREAD

**Issue by 3rain** [Zasilkovna/prestashop-1.6#33]
Dobrý den,
dnes jsem chtěl aktualizovat z verze 2.0.4 na poslední verzi 2.0.7. Začal jsem na localhostu, abych ověřil jak funguje.

Soubor Carrier.php v /override/classes před aktualizací obsahuje kód zásilkovny, ale i dalšího modulu pro Balíkovnu.
Zřejmě kvůli tomu se upgrade nepovedl a hlásil nemožnost smazáni přepisu.

Vymazal jsem z kódu část zásilkovny a povolil modul. Chyba zmizela. Ovšem od té doby se již nevkládá název pobočky do názvu dopravce, což je problém. Stejné je to i po navrácení původního souboru Carrier.php na místo.

Můžete prosím poradit? Děkuji

**Comment by packeta** [comment]
Dobrý den, 
override jsme odstranili záměrně.  O jeho vrácení neuvažujeme.  PrestaShop override nedoporučuje u modulů třetích stran,  tento způsob modifikace je vhodný spíše u vlastních pluginů.  Název vybraného výdejního místa zobrazujeme v potvrzení objednávky, v emailové potrzení objednávky (lze nastavit dle návodu: https://github.com/Zasilkovna/prestashop-1.6#jak-zobrazit-vybran%C3%A9-v%C3%BDdejn%C3%AD-m%C3%ADsto-v-emailu-potvrzen%C3%AD-objedn%C3%A1vky) .  
Výdejní místo se zobrazí také v detailu existující objednávky v historii objednávek přihlášeného uživatele.
Pokud by se vám zobrazení výdejního místa hodilo i na jiném místě,  napište nám na technicka.podpora@zasilkovna.cz, kde konkrétně vám zobrazení výdejního místa chybí (ideálně přidat screen).   Pokud to bude dávat smysl a funkce bude užitečná pro více uživatelů, rádi ji naplánujeme do některé další verze modulu.
