### ISSUE TITLE
Chyba v hooku hookActionGetExtraMailTemplateVars.

### ISSUE THREAD

**Issue by martin-tuma** [Zasilkovna/prestashop-1.6#39]
Pokud se modul zavěsí nakonec, tak přepíše proměnou pro všechny ostatní moduly a pole jen nerozšíří.
Připravil jsem fix, který toto řeší: https://github.com/Zasilkovna/prestashop-1.6/pull/38

**Comment by MatyasKoval** [comment]
Dobrý den @martin-tuma ,
za PR a opravu velice děkuji. 

Nicméně před zapracováním z naší strany nejdříve provedeme i otestování a CR.

S přáním krásného dne,
Matyáš Kovaľ - Zásilkovna E-Commerce Support

**Comment by martin-tuma** [comment]
Dobrý den,
děkuji za informaci.

S pozdravem
M. Tůma

**Comment by packeta-user** [comment]
Ještě jednou děkujeme za PR.  Vaši opravu jsme zahrnuli do https://github.com/Zasilkovna/prestashop-1.6/pull/40
