### ISSUE TITLE
Nefunguje výběr místa odběru - Slovensko

### ISSUE THREAD

**Issue by 3rain** [Zasilkovna/prestashop-1.6#9]
Dobrý den,
testuji modul zásilkovny na PS 1.6.1.10 na localhostu. Vytvořil jsem úspěšně objedávku pro českou republiku. Při výběru odběrného místa se správně načte popup s pobočkami.

Založi jsem další Zásilkovna dopravce, kde je vybráno i Slovensko (SK). Pokud zvolím v účtu adresu na Slovensku, dopravce se korektně zobrazuje. Po kliknutí na výběr odběrného místa se ovšem popup nenačte. Jeho UI jde vidět, ale vypadá, že se zasekne na stahování dat nebo data jen neumí zobrazit.

Zkoušel jsem použít stejnou zónu "Europe" pro Slovensko nebo jsem ho dal do samostatné zóny (což preferuji), v obou případech je stejný problém. Nezáleží, zda je dopravce nastaven pro CZ i SK nebo jen SK. Vždy se to pro Slovensko nepodaří načíst.

Na produkci jsem to zatím nenasadil, ale myslím, že se může jednat o chybu v modulu, když pro CZ to funguje správně.

Mohu vás poprosit o prověření? Děkuji

![image](https://user-images.githubusercontent.com/81020682/111869211-867aa000-897e-11eb-90b6-a8c868f4ee7a.png)

**Comment by packeta** [comment]
Dobrý den,  zkontrolujte si prosím, zda máte Slovensko povolené v nastavení účtu Zásilkovny zde:  https://client.packeta.com/cs/user-branch-settings/edit   .  Pokud zde nějakou zemi povolíte a změny uložíte,  ve widgetu se toto projeví až za několik hodin.

**Comment by 3rain** [comment]
Dobrý den,
máte pravdu, nastevení jsme změnili, ale nepočkali. Nyní už vidím, že se dialog správně načítá. Děkuji za radu.
